title: "Diagnosa Fenomena"
email: diagnosa.fenomena@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm a software engineer with interest in Web Development, Artificial Intelligence, 
  BioInformatics and Image Processing with ability to learn fast, adapt easily, 
  and also a TDD practicioner.
baseurl: "/" 
url: "https://diagnosa.github.io/" 
twitter_username: diagnosaf
github_username:  diagnosa

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg